# these are the core components of ESPPrint. Most are used for basic GCode communication.
# other packages may depend on components of this package.

esphome:
  on_boot:
    # wait until printer is up and running
    - delay: 4s
    # initialize gcode sender module
    - lambda: id(gcode_sender)->reset();
    # enable auto temperature report
    - lambda: id(gcode_sender)->sendGCode("M155 S4");

external_components:
  - source:
      type: local
      path: components

GCodeQueue:

# core components for sending GCodes
GCodeSender:
  id: gcode_sender
  uart_id: uart_bus
  resend_buffer_size: 8

# core component for receiving GCode responses
GCodeReader:
  id: gcode_reader
  uart_id: uart_bus

# forwards sent and received GCodes to Home Assistant for terminal card
GCodeEvents:

sensor:
- platform: M73_Progress
  name: "${printer_name} Print Progress"
- platform: M73_RemainingTime
  name: "${printer_name} Remaining Time"

climate:
- platform: GCodeClimate
  id: tool_temp
  name: "${printer_name} Tool Temperature"
  heater_element: tool
  visual:
    min_temperature: 0 °C
    max_temperature: 250 °C
    temperature_step: 1 °C
- platform: GCodeClimate
  id: bed_temp
  name: "${printer_name} Bed Temperature"
  heater_element: bed
  visual:
    min_temperature: 0 °C
    max_temperature: 80 °C
    temperature_step: 1 °C