# components for file storage. You can print GCodes files with this package.

# Filesystem of the Storage, currently tested filesystems are SD_MMC and SD for SPI card readers
SD:

# component to print GCode from storage
GCodeFileReader:
  id: gcode_file_reader
  cancel_gcodes: ["M104 S0", "M140 S0", "G28 X Y", "M84"]

# displays the file which is currently printing
text_sensor:
- platform: template
  name: "${printer_name} Current File"
  lambda: |-
    if (id(gcode_file_reader)->getFilename() == "")
      return {"None"};
    else
      return id(gcode_file_reader)->getFilename();
  update_interval: 10s

# component to enable filesystem card
FileAnalyzer:

#web_server_base:
#  id: upload_server_base
#
## http server for GCode upload
## this component fakes parts of the octoprint Rest API for compatiblity with slicers
#- id: upload_server
#  lambda: |-
#    auto upload = new storage::UploadServer(id(upload_server_base), get_fileReader(id(file_reader)), get_fileanalyzer(id(analyzer)));
#    App.register_component(upload);
#    return {upload};
